server:
  port: 8088

spring:
  application:
    name: react-spring
  datasource:
    url: jdbc:mysql://localhost:3306/mytime
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
